---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 106379
      nodePort: 32021
      name: redis
  selector:
    app: redis
    tier: backend
