---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  labels:
    app: redis-commander
    tier: backend
spec:
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32022
  selector:
    app: redis-commander
    tier: backend
